name: agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas
  - pyyaml
  - tqdm
  - rdkit
  - scipy<1.11
  - neo4j>=5.17
  - langchain-openai>=0.0.24
  - langgraph>=0.0.19
  - langsmith>=0.1.2
  - guacamol
  - pip:
    - cerebras-cloud-sdk
    - langgraph-checkpoint-sqlite

