# 全域設定 – 若要覆寫請用環境變數或 CLI
START_SMILES: C1CCCCC1                      # dummy seed，稍候由 prescan 覆寫
TASK_NAME: celecoxib                       # 默認測試任務

# MCTS / GRPO / UCT 參數
K_init: 8
p_top: 8
c_uct: 1.4
gamma_adv: 0.3
alpha_pw: 2
beta_pw: 0.6
grpo_eps: 0.2
max_depth: 15

# Oracle 設定
oracle_limit: 500
oracle_rate: 600_per_hour                  # 令牌桶
smi_file: /home/luketou/LLM_AI_agent/Agent_predictor/data/guacamol_v1_all.txt

# LLM 設定
llm:
  provider: cerebras  # 使用 cerebras 而不是 openai
  model_name: llama-3.3-70b
  temperature: 0.2
  max_completion_tokens: 2048
  top_p: 1
  stream: true
  api_key: csk-8f3ct6y23mw2fw3fdmyx8t4tx8rw8p85tdx9nrm8mv2t9m26

# LangSmith 設定
langsmith:
  project: mol-agent-v1
  api_key: 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

# Knowledge Graph 設定
kg:
  backend: neo4j
  uri: bolt://localhost:7687
  user: neo4j
  password: !ENV ${NEO4J_PASSWORD}
  database: neo4j