# 全域設定 – 若要覆寫請用環境變數或 CLI
START_SMILES: C1CCCCC1                      # dummy seed，稍候由 prescan 覆寫
TASK_NAME: celecoxib                       # 默認測試任務

# MCTS / GRPO / UCT 參數
K_init: 30 # number of smiles generated for each node
p_top: 8
c_uct: 1.4
gamma_adv: 0.3
alpha_pw: 2
beta_pw: 0.6
grpo_eps: 0.2
max_depth: 50  # search tree 最大深度

# Oracle 設定
oracle_limit: 500
oracle_rate: 600_per_hour                  # 令牌桶
smi_file: data/guacamol_v1_all.txt

# 工作流程設定
workflow:
  recursion_limit: 1000                     # LangGraph 遞迴限制，預設為 50
  max_iterations: 1000                     # 最大迭代次數
  early_stop_threshold: 0.9                # 早停閾值：找到此分數以上的分子就停止
  max_smiles_length: 100                   # SMILES 最大長度限制，超過此長度的分子將被過濾或終止
                                           # 建議值：50-150，太小會限制分子多樣性，太大會導致過於複雜的分子

# LLM 設定
llm:
  provider: cerebras  # 使用 cerebras 而不是 openai
  model_name: qwen-3-32b
  temperature: 0.2
  max_completion_tokens: 8192
  top_p: 1
  stream: true
  api_key: csk-8f3ct6y23mw2fw3fdmyx8t4tx8rw8p85tdx9nrm8mv2t9m26

# LangSmith 設定
langsmith:
  enabled: true
  tracing: true
  endpoint: "https://api.smith.langchain.com"
  project: "world model agent"
  api_key: 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

# Knowledge Graph 設定 (可選，如果無法連接會使用內存存儲)
kg:
  backend: neo4j
  uri: bolt://localhost:7687
  user: neo4j
  password: !ENV ${NEO4J_PASSWORD}
  database: neo4j
  enabled: false  # 在遠端 cluster 上禁用 Neo4j