# 全域設定 – 若要覆寫請用環境變數或 CLI
START_SMILES: C1CCCCC1                      # dummy seed，稍候由 prescan 覆寫
TASK_NAME: celecoxib                       # 默認測試任務
K_init: 8
p_top: 8
c_uct: 1.4
gamma_adv: 0.3
alpha_pw: 2
beta_pw: 0.6
grpo_eps: 0.2
max_depth: 15
oracle_limit: 500
oracle_rate: 600_per_hour                  # 令牌桶
smi_file: /home/luketou/LLM_AI_agent/Agent_predictor/data/guacamol_v1_all.txt

langsmith:
  project: mol-agent-v1
  api_key: !ENV ${LANGSMITH_API_KEY}

kg:
  backend: neo4j
  uri: bolt://localhost:7687
  user: neo4j
  password: !ENV ${NEO4J_PASSWORD}